
<!DOCTYPE html>
<html lang="en">
output:
<head>
  html_document:
    <meta charset="UTF-8">
    theme: flatly # specifies the theme
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
navbar:
    <title>Kashmiri Free Page</title>
  left:
    <style>
    - text: "Home"
        body {
      href: index.html
            font-family: Arial, sans-serif;
    - text: "Create a Project"
            margin: 0;
      href: project.html
            padding: 0;
    - text: "Set Build Options"
            background-color: #0c0101;
      href: build.html
        }
    - text: "Create a _site.yml"
        header {
      href: create_yml.html
            background: #35424a;
    - text: "Tables and Plots"
            color: #CECECE;
      href: tables_plots.html
            padding: 10px 0;
    - text: "Include Images"
            text-align: center;
      href: images.html
        }
    - text: "Embed a webpage"
        nav ul {
      href: embed.html
            list-style: none;
    - text: "Themes"
            padding: 0;
      href: theme.html
        }
    - text: "Publishing your site"
        nav ul li {
      href: publishing.html
            display: inline;
output_dir: "." # if publishing on Github pages
            margin: 0 15px;
Bear in mind that the more menu items we add the more the size of the navigation bar at the top will increase. This can lead to the page not displaying properly.
        }
        section {
            padding: 20px;
            margin: 10px;
            background: #ffffff;
            border-radius: 5px;
        }
        footer {
            text-align: center;
            padding: 10px 0;
            background: #26B69C;
            color: #ffffff;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to Muft Maal</h1>
        <nav>
            <ul>
                <li><a href="#about">About</a></li>
                <li><a href="#projects">Projects</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>
    <section id="about">
        <h2>About Me</h2>
        <p>Hello! My name is Amaan Tahir, and I am passionate about the transformative power of reading. As a dedicated book provider, I believe that access to literature should be universal and free for everyone. My mission is to make a diverse array of books available to readers of all ages and backgrounds, fostering a love for literature and learning.
 
 
            With a carefully curated collection that spans genres—from classic literature and contemporary fiction to informative non-fiction and enriching children's books—I strive to ensure that there is something for everyone. I understand the joy and inspiration that stories can bring, and I am committed to supporting your reading journey.
To solve this use sub-menus as in the _site.yml for this site (see below).

            Whether you're looking for a new favorite novel, a thought-provoking memoir, or resources for personal growth, I'm here to help you discover your next great read, all at no cost. Join me as we explore the wonderful world of books together—because everyone deserves the chance to experience the magic of reading!.</p>
    </section>
    <section id="projects">
        <h2>My Projects</h2>
 
 
        <p>### Project Overview: "A Vision for Accessible Literature"
name: "Create a simple Rmarkdown website"
navbar:
  left:
    - text: "Home"
      href: index.html
    - text: "Getting Started"
      menu:
        - text: "Create a Project"
          href: project.html
        - text: "Set Build Options"
          href: build.html
        - text: "Create a _site.yml"
          href: create_yml.html
    - text: "Add Features"
      menu: 
        - text: "Tables and Plots"
          href: tables_plots.html
        - text: "Include Images"
          href: images.html
        - text: "Embed a webpage"
          href: embed.html
    - text: "Publish and Update"      
      menu: 
        - text: "Publishing"
          href: publishing.html
        - text: "Updating"
          href: updating.html
output_dir: "."
The key to this is to open a new menu heading as follows and then specify the items. text refers to the text for the menu button and the menu will group the pages that you specify. Note that the tab indents matter and if something goes wrong you have probably forgotten the - text for the menu heading or to indent uniformly.
 
 
            #### Introduction
- text: "Publish and Update"      
            In a world where knowledge and stories can transform lives, I recognized a pressing need for greater access to literature, particularly for those who may face barriers in obtaining books. With this vision in mind, I embarked on a project that reflects my dedication and hard work in providing a free book service to communities in need. This project not only aims to supply books but also to foster a culture of reading and learning.
      menu: 

        - text: "Publishing"
            #### Background
          href: publishing.html
            Having always been an avid reader and a firm believer in the importance of literature, I understood how transformative books could be in shaping thoughts, expanding horizons, and encouraging empathy. However, I also saw that many individuals faced obstacles—be it financial constraints, lack of access to libraries, or limited exposure to diverse literature. This realization fueled my determination to make a change.
        - text: "Updating"

          href: updating.html
            #### Objectives
