name: "Enhanced Rmarkdown Website"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-R-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-
      - name: Install dependencies
        run: |
          Rscript -e "install.packages('rmarkdown')"
      - name: Build site
        run: |
          Rscript -e "rmarkdown::render_site()"
